apiVersion: v1
kind: Service
metadata:
  name: elastic-rest
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: transport-client
  selector:
    service: elasticsearch