apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-worker
  labels:
    app: load-worker
spec:
  selector:
    matchLabels:
      app: load-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: load-worker
    spec:
      containers:
      - name: load-worker
        image: berndruecker/zeebe-loadtest-worker:latest
        imagePullPolicy: Always
        env:
          - name: zeebe.brokerContactPoint            
            value: "zeebe-gateway:26500"
          - name: elasticsearch.url          
            value: "http://elastic-gateway:9200"
          - name: loadtest.type
            value: "worker"
          - name: loadtest.jobType
            value: "some-work"            
          - name: loadtest.numberOfClientNodes
            value: "1"
          - name: loadtest.numberOfWorkerThreads
            value: "1"
          - name: loadtest.workExecutionTimeInMillis
            value: "0"
          - name: loadtest.numberOfBrokerNodes
            value: "3"
          - name: loadtest.replicationFactor
            value: "3"
          - name: loadtest.numberOfPartitions
            value: "3"
          - name: loadtest.numberOfMachines
            value: "8"
          - name: loadtest.machineType
            value: "n1-standard-4"
          - name: loadtest.storage
            value: "local-machine"

