apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-starter
  labels:
    app: load-starter
spec:
  selector:
    matchLabels:
      app: load-starter
  replicas: 1
  template:
    metadata:
      labels:
        app: load-starter
    spec:
      containers:
      - name: load-starter
        image: berndruecker/zeebe-loadtest-starter:latest
        imagePullPolicy: Always
        env:
          - name: zeebe.brokerContactPoint            
            value: "zeebe-gateway:26500"
          - name: elasticsearch.url          
            value: "http://elastic-gateway:9200"
          - name: loadtest.type
            value: "starter"
          - name: loadtest.numberOfClientNodes
            value: "1"
          - name: loadtest.numberOfBrokerNodes
            value: "3"
          - name: loadtest.replicationFactor
            value: "3"
          - name: loadtest.numberOfPartitions
            value: "3"
          - name: loadtest.numberOfMachines
            value: "8"
          - name: loadtest.machineType
            value: "n1-standard-4"
          - name: loadtest.storage
            value: "local-machine"