apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-worker
  labels:
    app: load-worker
spec:
  selector:
    matchLabels:
      app: load-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: load-worker
    spec:
      containers:
      - name: load-worker
        image: berndruecker/zeebe-loadtest-worker:latest
        imagePullPolicy: Always
        env:
          - name: zeebe.brokerContactPoint            
            value: "zeebe-gateway:26500"
          - name: elasticsearch.url          
            value: "http://elastic-gateway:9200"
          - name: elasticsearch.currentConfigDescription
            value: "worker: 1, nodes: 3, replication, partitions: 3"

