apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeebe
  labels:
    app: zeebe
spec:
  serviceName: "zeebe"
  selector:
    matchLabels:
      app: zeebe
  replicas: 3
  template:
    metadata:
      labels:
        app: zeebe
    spec:
      containers:
      - name: zeebe
        image: camunda/zeebe:0.12.1
        ports:
        - containerPort: 26500
          name: gateway
        - containerPort: 26501
          name: client
        - containerPort: 26502
          name: management
        - containerPort: 26503
          name: replication
        - containerPort: 26504
          name: subscription
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ZEEBE_CLUSTER_SIZE
            value: "3"
          - name: ZEEBE_PARTITIONS_COUNT
            value: "3"
          - name: ZEEBE_REPLICATION_FACTOR
            value: "3"
          - name: ZEEBE_CONTACT_POINTS
            value: "zeebe-0.zeebe:26502"
          - name: ZEEBE_LOG_LEVEL
            value: info
        command:
          - "/bin/sh"
          - "-c"
          - "export ZEEBE_NODE_ID=$((${MY_POD_NAME##*-})) && /usr/local/bin/startup.sh"

